/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-msoffice-crypt.h
 #	source generated by 4D Plugin Wizard
 #	Project : msoffice crypt
 #	author : miyako
 #	2021/11/01
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_MSOFFICE_CRYPT_H
#define PLUGIN_MSOFFICE_CRYPT_H

#include "4DPluginAPI.h"

#pragma mark -

/**
    @file
    @brief MS Office encryption encoder/decoder
    Copyright (C) 2012 Cybozu Labs, Inc., all rights reserved.
*/

#include <stdio.h>
#include <stdlib.h>
#include <string>
#include <locale>
#include <fstream>
#include <cybozu/mmap.hpp>
#include <cybozu/file.hpp>
#include <cybozu/atoi.hpp>
#include <cybozu/option.hpp>
#include "cfb.hpp"
#include "decode.hpp"
#include "encode.hpp"
#include "make_dataspace.hpp"
#ifdef _MSC_VER
#include <cybozu/string.hpp>
#endif

#include "C_BLOB.h"
#include "C_TEXT.h"

#include "4DPlugin-JSON.h"

static void msoffice_crypt(PA_PluginParameters params, int enc = 1);

#endif /* PLUGIN_MSOFFICE_CRYPT_H */
